// GENERATED by peregrine-planner/scripts/build-help-content.mjs -- do not edit by hand.
// Edit the data in that script and re-run it; it rewrites both this file and the app's
// HelpContent.json so the app and this website stay in sync.
window.HELP_CONTENT = {
  "quickStart": [
    {
      "title": "Start on the Plan tab",
      "body": "The Plan tab opens on a “Notable birds near you” card — a live count of the locally rare or unusual species reported nearby, straight from your device location with nothing to set up. Tap “See them on the map” to open Notable Birds Nearby (the Species Map filtered to just those sightings, with a species picker). Below the card, Recent reports lists every recently-reported species, with a search box, a start-location button, and a lookback control."
    },
    {
      "title": "Pick birds and plan a trip",
      "body": "Tap any bird in Recent reports to select it, then tap “Plan Trip” at the bottom. That opens a short form — trip length and start date, plus an optional “leave out” list for birds you've already seen or hotspots you've already visited — with “Generate plan” (uses your selected birds) and “Auto-Plan” (lets the app pick the stops). The Plan tab's action bar also has the full Species Map (every species) and the Hotspot Browser."
    },
    {
      "title": "Identify what you see or hear",
      "body": "The Identify tab has four tools on one screen: Sound (real-time BirdNET audio detection), Photo (batch photo analysis), AR (live camera overlay), and Ask (a conversational AI assistant). All results are experimental — verify with a field guide or an expert birder."
    },
    {
      "title": "Keep your records on the Log tab",
      "body": "The Log tab opens on your trip list; the title menu switches between Trips, Trip Map, Life List, State Birds, Big Month, and Photos. The ••• button at the top-left holds Behaviors, Migration, and Tell Your Story."
    },
    {
      "title": "Learn and take on challenges",
      "body": "The Learn tab has Learn About Birds (flashcards + a photo-and-field-marks quiz with spaced review), Practice Observing, the guided trip walkthrough, a Practice & Ask row that jumps to the assistant or Sound / Photo / AR, and daily / weekly / monthly Bird Challenges that track themselves. Your badge and daily streak reflect real progress across the app."
    },
    {
      "title": "Settings, appearance, and hardware",
      "body": "Open Settings from the gear button at the top-right of any tab to set your home state, manage notifications, and back up your data. The app follows your device's Light or Dark appearance automatically — there's no separate toggle. The optional DIY directional mic array is enabled here too; when it's on, Mic Array becomes its own tab."
    }
  ],
  "birdingTips": [
    "Go out in the first few hours after sunrise — that's when most birds are singing and feeding.",
    "Learn the common birds cold first; knowing what's usual makes the unusual jump out.",
    "Listen before you look. Many birds are heard long before they're seen, and calls are often the quickest ID.",
    "Note shape, size, and behavior before color — light distorts color, but a silhouette and how a bird moves rarely lie.",
    "Move slowly and pause often. Stopping for a few minutes in one spot turns up more than walking steadily.",
    "Check habitat and season. The same field guide page means different things in a marsh in May versus a woodlot in November.",
    "Use the app's Sound, Photo, and AR tools as a second opinion, then confirm with a field guide — they're aids, not authorities.",
    "Keep notes. Writing down what you saw fixes it in memory far better than a quick glance and a mental 'got it'."
  ],
  "guideSections": [
    {
      "title": "Plan Tab",
      "description": "Opens on a zero-config “Notable birds near you” card, then the full list of recently-reported species. All data is live from eBird.",
      "details": [
        "Notable birds near you (the card at the top): shows how many locally rare or unusual species have been reported nearby recently, out of the total reported. It works from your device location with nothing selected.",
        "Tap “See them on the map” on that card to open Notable Birds Nearby — the Species Map filtered to just the notable sightings, with a species picker so you can pin down which bird is where. The button is hidden when nothing notable has turned up.",
        "Recent reports (below the card): the search box finds a specific species by name; the start-location button changes where “nearby” is centred; the day chips (1, 3, 7, 14, 30) set how far back the observations go.",
        "Tap any bird in the list to select it for a trip; the action bar also has the full Species Map (every species, not just notable) and the Hotspot Browser."
      ]
    },
    {
      "title": "Identify Tab — Bird Identification",
      "description": "AI-powered identification tools for birds you encounter in the field, as an in-screen mode switch (Sound / Photo / AR / Ask). All results are experimental and should be verified with field guides or expert birders.",
      "details": [
        "Sound: real-time audio listening using the Cornell BirdNET model. Choose a sensitivity level, grant microphone and notification permissions, and detected species appear live with confidence scores. Detections build a trip log you can save or merge into an existing trip. If you've paired the optional directional mic array accessory, tap the location icon next to a detected species to see which direction it's coming from.",
        "Photo: select up to 20 photos (or take new ones) for batch AI analysis; results are grouped by species with confidence scores.",
        "AR: point your camera at a bird for live species identification with a confidence-score overlay, in continuous, tap-to-detect, or manual capture modes. If location is available, a detection may also show “Not recently reported near you” — meaning that species hasn't been reported in eBird activity near you in the last two weeks. That never changes the confidence score itself, just flags it as worth a second look.",
        "AR camera presets tune the live camera for a shooting situation: Large Soaring Birds, Medium Birds – Moderate Distance, Hummingbirds in Flight, Perched or On the Ground, Digiscoping, or Auto. Each sets a shutter-speed ceiling, exposure compensation, and white balance; Digiscoping also turns autofocus off and locks the lens at infinity so a spotting scope's own focus knob is the only focus control. Your choice is remembered between sessions.",
        "AR keeps every capture that clears the confidence threshold (up to a dozen of the best per species), and all of them save to the trip log. In tap-to-detect or manual capture mode, a shot below the threshold goes to a “Needs ID” strip instead of being discarded — tap it to pick another guess, search the full species list, or discard it. “Add Species Manually” lets you name a bird the model can't.",
        "Ask (AI Bird ID Assistant): a conversational assistant for identification questions, comparisons, habitat, and behavior — “What does a Cardinal look like?”, “How do I tell Cooper's Hawk from Sharp-shinned Hawk?” It remembers the conversation, so a follow-up like “what about its habitat?” works, and it can check your own trip logs (“Have I seen a Painted Bunting?”). On Apple Intelligence-capable devices answers are more natural and tagged “Enhanced by Apple Intelligence”; otherwise it uses the app's built-in bird database.",
        "Behavior and migration observations are recorded on the Log tab (the ••• menu → Behaviors / Migration), not here — see “Behavior Logging” and “Migration Tracking” below."
      ]
    },
    {
      "title": "Directional Mic Array (Optional Hardware Accessory)",
      "description": "Pair a separately-built ESP32-S3 4-microphone accessory to see which direction a detected bird call is coming from during Sound detection. This is a DIY hobbyist build, not a commercial product. When it's enabled in Settings, Mic Array becomes its own tab that brings the sections below together.",
      "details": [
        "Requires the standalone hardware accessory — download the firmware and wiring instructions below. Not needed for any other app feature.",
        "Enable it from Settings > Mic Array, then join the array's Wi-Fi network in your device's Wi-Fi settings — “PeregrineMicArray” / “birding123” for the original front array, or whatever network name and password was configured on a camera-node accessory that hosts its own network instead.",
        "Once connected, start a Sound detection session as normal, then tap the location icon next to any detected species to track its direction — an arrow shows the azimuth (relative to the mic array's own forward-facing mark, not true north) along with a getting closer / farther / steady trend.",
        "Direction only updates when the app confirms a fresh detection of the species you're tracking, not on every sound the array picks up — so it can lag slightly behind, by design, rather than jumping around on unrelated noise.",
        "The “Direction Sensitivity” slider in the Mic Array settings screen controls how confident a reading needs to be before it's shown at all — lower it for more frequent (noisier) updates, raise it for fewer but more reliable ones.",
        "Radar Mode: instead of tracking one species at a time, shows a live bearing for up to 4 currently-calling species at once, each isolated by that species' typical call frequency so a busy multi-bird soundscape doesn't collapse into a single loudest-sound reading. Toggle it on from the Sound detection screen while the array is connected; it runs alongside single-species tracking, not instead of it.",
        "Sound source: while the mic array (or any connected fleet node) is available, Sound detection shows a “Sound source” picker — choose whether the Primary array or a specific Additional Node feeds the screen. Direction tracking and Radar Mode follow whichever source you pick.",
        "Mic Array Map: once two or more GPS-equipped nodes are connected, a map view (reachable from Sound detection) plots each node's real position and current bearing and, when their bearings line up, an estimated position for the sound — the geolocated counterpart to the phone-centered direction arrow.",
        "Self-Test: the Mic Array settings screen has a clap test — clap near one side of the array and confirm the azimuth number moves before you head into the field.",
        "GPS status: a node with a GPS module shows a live fix / no-fix readout with satellite counts and antenna / sky-view guidance, so a node that never acquired a fix is obvious before you rely on it.",
        "Left / right direction only — the array can't determine front / back or true compass heading, and there's no distance or elevation measurement.",
        "Learned Frequency Bands: the app remembers the actual call frequency range measured for each species you've tracked, and — once “Seed Tracking from Learned Data” is turned on in the Mic Array settings screen — uses that real history instead of a general per-species estimate once enough confirmed detections have accumulated. Recording happens automatically in the background regardless of the toggle. “Reset Learned Data” in the same screen clears it."
      ],
      "downloadHref": "peregrine-mic-array-firmware.zip",
      "downloadLabel": "Download Firmware (.zip)"
    },
    {
      "title": "Multi-Node Fleet & Camera Nodes",
      "description": "Beyond the single front array, the app can run a small fleet of DIY nodes — extra mic arrays and camera-equipped nodes — at the same time. All of this is optional and needs the separately-built hardware.",
      "details": [
        "Manage Additional Nodes: Settings > Mic Array > Additional Mic Array Nodes. Add a node by name, type (mic-only or camera), and network address, or tap Auto-Discover to find nodes already on your shared Wi-Fi — discovery also works over Bluetooth before anything is connected. A node whose IP address changes is re-matched automatically rather than showing up as a new one.",
        "Heading Source (set per node, and for the Primary array in its own settings screen): Fixed Pin (stand at the node and tap “Set from my current location” to capture its position and facing from your phone's GPS and compass — used whenever the node's own GPS has no fix), Phone Proxy (the node is carried with your phone and borrows its live GPS position and compass heading), Manual Heading Only (records a mounting heading but no position, so the node won't appear on the map), or Compass (reserved for future hardware). A real node GPS fix always takes over automatically when one is available, and a Fixed Pin re-syncs from that fix if the node is later moved.",
        "Camera section of the Mic Array tab: the field screen for the camera side of the hardware — live capture for the Primary array and every declared camera node in one place, plus the two review inboxes. (Feeder Cam Mode and its Home Assistant URLs stay in Settings > Mic Array.)",
        "Camera nodes — capture mode: from the Mic Array tab's Camera section, set each node to Auto (it photographs a bird on its own when its audio / motion detection fires) or Manual only. “Take Photo Now” works in either mode.",
        "Camera nodes — video: Start / Stop Video from the Mic Array tab's Camera section. Recording runs on the node itself and keeps going even if you leave the screen.",
        "Camera nodes — Live Preview: a rough live image for confirming a camera is aimed and focused while you physically set it up. It is not smooth video, and it is unavailable while the node is recording.",
        "Camera Node Captures (photo inbox): auto-captured photos wait here for review. For each one, Save adds it to a trip with the on-device species guess, “Not a Bird” routes it into a Tell Your Story journal instead, and Discard deletes it.",
        "Camera Node Videos (video inbox): recorded clips wait here — play a clip inline, share it out through the iOS share sheet, or Save it into a trip as a sighting you identify yourself (no automatic species ID runs on video).",
        "Field Debug (Mic Array Nodes > Field Debug): turn on remote logging per node and watch a live tail of what each node reports, filter or search the lines, and share the full or filtered log out of the app. It also shows per-node AI classify latency once the Sound detection model has been loaded."
      ]
    },
    {
      "title": "Trip Trail Recording",
      "description": "Records the GPS path you actually walk during a trip, separate from the stops you log.",
      "details": [
        "Recording starts automatically when you tap “Start Trip” on a saved trip and stops when you tap “Finish Trip”.",
        "View it afterward from the trip's detail screen via “View Trip Trail” — your path is drawn as a line, and any fleet nodes that were reporting a position during the trip appear as pins where they were placed.",
        "This is per-trip and distinct from Log > Trip Map, which plots your logged locations across every trip."
      ]
    },
    {
      "title": "Learn Tab",
      "description": "Structured learning activities for birders of all levels, with a real daily streak, a birder badge, and links straight into the identification tools.",
      "details": [
        "Learn About Birds: study 5 common species near you (from real eBird observations), then take a 10-question quiz — including photo-ID questions and “which bird has these field marks” questions, with wrong answers drawn from each species' confusion species. Pass at 80%. Birds you learn come back for spaced review; birds you miss come back sooner, and the results screen lists exactly which ones to look at again.",
        "Each studied bird opens the full species card (facts, range, similar species, external links) and an “Ask the assistant about this bird” button.",
        "Practice Observing: a guided listen → observe → describe → compare exercise using real-time sound detection.",
        "Plan Your Trips: the same guided 3-level trip walkthrough that's also on the Plan tab under “Plan Trip” → “Guided walkthrough”.",
        "Practice & Ask: jump straight to the AI assistant or to Sound / Photo / AR identification.",
        "Bird Challenges: daily, weekly, and monthly challenges that track themselves as you use the rest of the app.",
        "Your badge (New Birder → Birding Expert) reflects birds mastered, species on your Life List, challenges completed, and activities done — not just replayed points. A day-based streak counts consecutive days you open the Learn tab or finish an activity."
      ]
    },
    {
      "title": "Trip Planning",
      "description": "Select birds, set a duration, and generate an optimized multi-stop itinerary.",
      "details": [
        "Select birds from the Plan tab or the Hotspot Browser, then tap “Plan Trip” at the bottom of the Plan tab.",
        "In the sheet that opens, the “Trip” section sets the number of days, locations per day, the start date, and — when your device location differs from your search start — whether to start the route from where you are now.",
        "The “Leave out” section optionally excludes birds you've already seen or hotspots you've already visited.",
        "Tap “Generate plan” to build an itinerary from your selected birds, or “Auto-Plan” to let the app ignore the selection and pick the best nearby locations for you.",
        "Review the generated itinerary — day-by-day stops, estimated travel time, and likely birds at each location — then save it."
      ]
    },
    {
      "title": "App Navigation",
      "description": "Four bottom tabs — Learn, Plan, Identify, Log — plus a Mic Array tab when the hardware accessory is enabled in Settings. Settings and Help & Info are behind the gear button at the top-right of every tab.",
      "details": [
        "Learn — guided activities and challenges.",
        "Plan — notable birds near you, recent reports, and trip planning.",
        "Identify — Sound, Photo, AR, and Ask identification tools on one screen.",
        "Log — Trip Logs, Trip Map, Life List, State Birds, Big Month, and Photos via the title menu; Behaviors, Migration, and Tell Your Story via the ••• button.",
        "Mic Array — only visible when “Enable Mic Array Integration” is on in Settings; brings the directional mic array, the fleet, and the camera nodes together.",
        "Gear button (every tab, top-right) — Settings and this Help & Info screen."
      ]
    },
    {
      "title": "Trip Map",
      "description": "A visual overview of your birding trips on an interactive map, showing only locations where you've actually logged sightings.",
      "details": [
        "On the Log tab, choose Trip Map from the title menu and load the map to see your logged locations as markers.",
        "Each marker shows the location name and how many birds were logged there.",
        "Tap a trip in the list below the map to highlight just that trip's locations."
      ]
    },
    {
      "title": "Trip Logs",
      "description": "View and manage all your saved birding trips, mark birds as seen, and add notes / photos.",
      "details": [
        "Tap any saved trip to view its details and check off birds as you see them.",
        "Add notes, counts, and photos to any sighting.",
        "Use the “Add Sighting” flow to log birds outside of planned trips — pick a location on the map, name it, and save.",
        "Mark a trip complete when you've finished it; completed sightings roll up into your Life List automatically.",
        "Use the search bar at the top of Trip Logs to quickly find a trip by name, location, or species seen.",
        "If you've logged the same outing twice (e.g. once manually and once via eBird import), use Settings > Advanced > Find & Combine Similar Trips to review same-day, same-location matches and merge them — every sighting and photo from each trip is kept, nothing is discarded."
      ]
    },
    {
      "title": "Import & Export",
      "description": "Trips can be exported as JSON files (for sharing with other app users), shared as plain text via the standard iOS share sheet, or added to your calendar as day-by-day events. PDF export is not currently available.",
      "details": [
        "Export: open a trip, use the share action, and choose JSON file, plain-text summary, or Add to Calendar.",
        "Add to Calendar creates one all-day event per day of the trip, listing that day's stops and target birds, in a “Birding Trips” calendar.",
        "Import: from Trip Logs, use the import button and select a .json trip file — trip and bird metadata are preserved, but not photos or personal notes / seen status (see Data Backup & Migration below for a format that keeps everything)."
      ]
    },
    {
      "title": "Data Backup & Migration",
      "description": "A full export of everything on this device — every trip (with photos and personal notes / seen status intact, unlike the sanitized trip JSON export above), behavior and migration logs, stories, hotspot notes, challenge progress, and app settings — as one file, for moving to a new phone.",
      "details": [
        "Access it from Settings > Advanced > Data Backup & Migration.",
        "Export All Data generates the file and opens the share sheet — AirDrop it to your new phone, save it to Files / iCloud Drive, or email it to yourself.",
        "On your new phone (with the app installed), use Import All Data and select the file.",
        "Importing REPLACES all data currently on that device — it's meant for setting up a new phone, not merging two devices' data together. If the device you're importing into already has data you care about, export a backup of that first.",
        "This is separate from per-trip JSON export / import above, which is meant for sharing individual trips with other app users, not full-device migration."
      ]
    },
    {
      "title": "Species Map",
      "description": "Shows recent eBird observations on an interactive map to help you explore sightings across your area.",
      "details": [
        "Open the full map (every reported species) from the Species Map button in the Plan tab's action bar.",
        "Open the filtered view, Notable Birds Nearby, from “See them on the map” on the Plan tab's Notable birds card — it shows only the locally rare or unusual sightings, with a species picker to narrow to one bird.",
        "Explore observation markers to help plan where to go birding next."
      ]
    },
    {
      "title": "Behavior Logging",
      "description": "Record detailed observations of bird behaviors — feeding, nesting, social interaction, and 11 other categories — for research and monthly challenges.",
      "details": [
        "On the Log tab, tap the ••• button (top-left) and choose Behaviors, then use the Record tab: select a species, choose a behavior type, and describe what you observed.",
        "Use the built-in timer to record observation duration accurately.",
        "Behavior logs are independent of trips and automatically contribute to monthly “Behavior Observer”-style challenges.",
        "Review past entries on the History tab of the same screen (a save flips you there automatically)."
      ]
    },
    {
      "title": "Migration Tracking",
      "description": "Record migratory bird movements — status, direction, flock size, altitude, and season — for research and monthly challenges.",
      "details": [
        "On the Log tab, tap the ••• button (top-left) and choose Migration, then use the Record tab: select a species and record its migration status (actively migrating, staging, arriving, departing, overwintering, at breeding grounds, or vagrant).",
        "The app automatically detects the current season for context.",
        "Migration logs are independent of trips and contribute to monthly migration-tracking challenges.",
        "Review past entries on the History tab of the same screen."
      ]
    },
    {
      "title": "Bird Challenges",
      "description": "Daily, weekly, and monthly birding challenges that automatically track your progress across the whole app.",
      "details": [
        "Daily challenges (identification, sound detection, photo capture) reset every day.",
        "Weekly challenges (species diversity, habitat exploration, rare-bird discovery) reset every Monday.",
        "Monthly challenges (behavior study, migration tracking) reset on the 1st of each month.",
        "Progress updates automatically as you log sightings, use AI detection, or record behavior / migration observations — no manual tracking needed.",
        "Access challenges from Learn > Bird Challenges to see live progress bars and point totals."
      ]
    },
    {
      "title": "Log Tab: Trip-Based vs. Standalone Observations",
      "description": "The Log tab separates regular birding-trip activity from focused research logs.",
      "details": [
        "Trip-based: Trip Logs, Trip Map, Life List, State Birds, Big Month, Photos — general birding activity that builds your Life List and can be shared / exported.",
        "Standalone research logs: Behaviors and Migration (the ••• menu) — detailed scientific observations, independent of any trip, that feed the monthly research challenges."
      ]
    },
    {
      "title": "Life List",
      "description": "A record of every bird species you've marked as seen, across all your trips.",
      "details": [
        "On the Log tab, choose Life List from the title menu.",
        "Tap any bird's thumbnail to see a detailed species card with identification info and photo sourcing.",
        "Tap a bird entry to see the locations and dates you've spotted it, with a link back to the original trip log.",
        "Tap the share icon to export your full life list as a CSV (species, scientific name, first-seen date, sighting count) — handy for comparing against your eBird life list."
      ]
    },
    {
      "title": "Big Month",
      "description": "Automatically tracks unique species you've seen each calendar month, based on when you marked birds as seen in your trip logs.",
      "details": [
        "On the Log tab, choose Big Month from the title menu.",
        "Each species counts once per month regardless of how many times you see it."
      ]
    },
    {
      "title": "Photo Gallery",
      "description": "Organizes all photos attached to your bird sightings, browsable by species.",
      "details": [
        "On the Log tab, choose Photos from the title menu.",
        "Tap any photo to view it full-screen along with species, location, and trip details; swipe left / right to move through the set.",
        "Switch between grid and list layout, and use the sort control (the up / down arrows in the toolbar) to order photos by newest, oldest, species A–Z or Z–A, or by which species has the most photos. Your choice is remembered."
      ]
    },
    {
      "title": "Hotspot Browser",
      "description": "Explore nearby birding hotspots and the species recently observed there.",
      "details": [
        "Open it from the Plan tab's action bar.",
        "Browse hotspots sorted by distance or species count, then add birds from a hotspot directly to your trip plan."
      ]
    },
    {
      "title": "State Birds Goals",
      "description": "Track your progress toward seeing every official state bird species from the eBird taxonomy.",
      "details": [
        "Set your home state first in Settings.",
        "On the Log tab, choose State Birds from the title menu — seen birds are marked with a checkmark, unseen birds are grayed out.",
        "Filter to see only seen or only unseen birds."
      ]
    },
    {
      "title": "Settings",
      "description": "Open Settings from the gear button at the top-right of any tab — your hub for app preferences and support.",
      "details": [
        "Profile: your display name (shown as “exported by” on trips you share as JSON) and your home state (used by State Birds Goals, and as a fallback species source for Learn About Birds).",
        "App Settings toggles: Show Rarity Scores (star / difficulty indicators on bird lists), Bird Detection Alerts (notify when a species is detected during a Sound session), Auto-Remove Unseen Birds (drop still-unseen birds automatically when you complete a trip), and Bird Image Thumbnails (download iNaturalist photos — off shows letter placeholders).",
        "Appearance: the app follows your device's Light or Dark setting automatically — there is no separate in-app toggle.",
        "AI Bird ID Assistant: the Smart Assistant toggle — on uses Apple Intelligence for more natural answers where the device supports it, off always uses the built-in bird database.",
        "Mic Array (Hardware Accessory): “Enable Mic Array Integration” turns on the optional directional microphone array and its setup / status screen. While it's on, Mic Array is also a bottom tab; while it's off, that tab is hidden and nothing about the accessory is shown.",
        "Your Birding Stats: a quick count of total trips, completed trips, birds seen, and unique species. Support the App: an optional tip jar.",
        "Settings > Advanced (collapsed by default): Find & Combine Similar Trips, Remove Duplicate Trips, Re-check for Previous App Data, Image Cache Management, Data Backup & Migration, and Clear All Data.",
        "Help & Info: this screen — Quick Start, User Guide, FAQ, and Contact Support, plus a keyword search box and, on Apple Intelligence devices, a plain-language question box."
      ]
    },
    {
      "title": "Data Attribution & Image Sources",
      "description": "Bird observation data comes from eBird.org (a Cornell Lab of Ornithology citizen-science project); bird thumbnail images come from iNaturalist.org, used under Creative Commons licensing with photographer credit shown in the app.",
      "details": [
        "Contribute your own sightings at eBird.org.",
        "Contribute bird photos at iNaturalist.org to help improve coverage for everyone."
      ]
    }
  ],
  "faqCategories": [
    {
      "name": "Getting started",
      "faqs": [
        {
          "id": "1",
          "question": "What is the “Notable birds near you” card on the Plan tab?",
          "answer": "It is the first thing on the Plan tab and it works with nothing set up: from your device location it counts the locally rare or unusual species reported nearby in your chosen lookback window (shown as “N notable of M species”). Tapping “See them on the map” opens Notable Birds Nearby — the Species Map filtered to just those sightings, with a species picker so you can tell which bird is where. The card and its button only appear when there is something notable to show; otherwise the Plan tab just shows the Recent reports list."
        },
        {
          "id": "2",
          "question": "How do I plan my first birding trip?",
          "answer": "Open the Plan tab. The “Notable birds near you” card at the top needs nothing set up — it uses your device location to show what rare or unusual birds are around right now; tap “See them on the map” to see them. To build an actual itinerary, use the Recent reports list below: optionally set a start location and lookback window, tap the birds you want, then tap “Plan Trip” at the bottom. That opens a form for trip length and start date, plus an optional “Leave out” list (birds you've already seen, hotspots you've already visited), with “Generate plan” (from your selected birds) and “Auto-Plan” (app picks the stops). The Learn tab also has a guided trip-planning tutorial for new birders."
        },
        {
          "id": "3",
          "question": "What is the Species Map and how do I access it?",
          "answer": "The Species Map plots recent eBird observations on an interactive map so you can see which birds are being reported where. Open the full map (every species) from the “Species Map” button in the Plan tab's action bar. There is also a filtered view, “Notable Birds Nearby”, reached from the “See them on the map” button on the Plan tab's Notable birds card — it shows only the locally rare or unusual sightings, with a species picker to narrow to one bird."
        },
        {
          "id": "4",
          "question": "How does the app determine which birds I might see?",
          "answer": "The app uses recent observation data from eBird.org to show birds reported near your location within your selected time frame (1–30 days). eBird is a project of the Cornell Lab of Ornithology that collects bird observations from birdwatchers worldwide."
        },
        {
          "id": "5",
          "question": "Can I change the location for my trip?",
          "answer": "Yes — tap the location button in the Plan tab's action bar to open the location picker. You can tap anywhere on the map to set a custom location or use your current location. If you have both set, you can choose to start your route from your current location instead of your search location."
        },
        {
          "id": "6",
          "question": "What do the rarity indicators mean?",
          "answer": "Birds are assigned rarity scores based on recent eBird observation data, with rarer species highlighted with a star indicator in bird lists and itineraries."
        },
        {
          "id": "7",
          "question": "What are hotspots and how do I use them?",
          "answer": "Hotspots are locations known for good birding, usually with many reported sightings. Use the Hotspot Browser (from the Plan tab's action bar) to explore nearby hotspots and see which birds have been spotted there recently — select a hotspot's birds to add them to your trip plan."
        },
        {
          "id": "8",
          "question": "What is the Learn tab and how does it help new birders?",
          "answer": "The Learn tab offers structured activities: “Learn About Birds” (study 5 local species, then a photo-and-field-marks quiz with spaced review), “Practice Observing” (link a sound to a bird in the field), “Plan Your Trips” (the guided trip walkthrough, also on the Plan tab), and “Bird Challenges”. A Practice & Ask row jumps straight to the AI assistant or to Sound / Photo / AR identification, and a daily streak plus a birder badge track your progress."
        }
      ]
    },
    {
      "name": "Identifying birds",
      "faqs": [
        {
          "id": "9",
          "question": "How do I use the AI bird identification features?",
          "answer": "The Identify tab has four AI-powered tools on one screen: Sound (real-time audio), Photo (photo analysis), AR (live camera overlay), and Ask (the conversational AI Bird ID Assistant). All are experimental and should be validated with field guides."
        },
        {
          "id": "10",
          "question": "How accurate is the AI bird identification?",
          "answer": "AI bird identification is experimental and should always be validated. Sound detection uses the Cornell BirdNET model; photo identification uses a Google AIY vision model. Accuracy depends on audio / image quality, background noise, lighting, and bird visibility. Confidence scores indicate the model's certainty, but even high-confidence results should be verified with field guides or expert birders."
        },
        {
          "id": "11",
          "question": "How do I use the real-time bird sound detection?",
          "answer": "Go to Identify > Sound and tap Start to begin listening. Grant microphone permissions when prompted. Choose your sensitivity level — High detects more birds but may include false positives, while Low is more conservative. Detected species appear with confidence scores, and non-bird sounds (traffic, human voices, other animals) are automatically filtered out. When you stop, detected birds are saved to a trip log, which you can merge into an existing trip or keep separate."
        },
        {
          "id": "12",
          "question": "How does bird sound identification work?",
          "answer": "Peregrine Planner uses BirdNET, a machine learning model trained on millions of bird vocalizations, to identify species from audio. Identify > Sound continuously listens and identifies species in real time as you record."
        },
        {
          "id": "13",
          "question": "How accurate is the bird sound identification and what factors affect it?",
          "answer": "Bird sound identification uses BirdNET, trained on millions of bird vocalizations and capable of identifying thousands of species. Accuracy improves during peak bird activity (dawn / dusk), with less background noise, and with longer recordings that capture a complete vocalization. Confidence scores indicate certainty — multiple detections of the same species increase confidence."
        },
        {
          "id": "14",
          "question": "What are the smart features of AI sound detection?",
          "answer": "Identify > Sound filters out non-bird sounds (human voices, traffic, machinery, other animals) automatically, so your detection list contains only actual bird species. It sends lock-screen notifications for new detections and supports enhanced processing mode for improved accuracy via cross-window voting."
        },
        {
          "id": "15",
          "question": "How do I use AI bird photo identification?",
          "answer": "Go to Identify > Photo to identify birds from your photos. Select up to 20 photos from your gallery, or take new ones with the camera. The AI analyzes each image and groups results by species with confidence scores. For best results, use clear, well-lit photos showing the bird prominently. Save results to a new or existing trip. Remember AI identification is experimental and should be verified with field guides."
        },
        {
          "id": "16",
          "question": "How do I use AR Bird Identification?",
          "answer": "Go to Identify > AR and grant camera permissions to begin. Point your camera at a bird to see a live species name and confidence score. Choose continuous detection (automatic, on a timer), tap-to-detect, or manual capture mode, and adjust the confidence threshold to control sensitivity. Pick a camera preset (Large Soaring Birds, Hummingbirds in Flight, Perched or On the Ground, Digiscoping, or Auto) to tune shutter speed, exposure, white balance, and focus for the situation. Every capture that clears the threshold is kept, and shots that don't clear it — plus the “Add Species Manually” button — let you name the bird yourself. When you're done, save your session's detections to a trip log."
        },
        {
          "id": "17",
          "question": "What do the AR Bird Identification camera presets do?",
          "answer": "They tune the live camera for a shooting situation. Large Soaring Birds, Medium Birds – Moderate Distance, and Hummingbirds in Flight each set a fast shutter-speed ceiling and a slight negative exposure compensation to freeze motion and protect highlights; Perched or On the Ground uses a slower ceiling and neutral exposure; Auto applies no manual control. Large Soaring Birds also locks white balance to daylight. Because iPhones have a fixed aperture and give apps no way to cap auto-ISO, the ISO ranges shown are targets the camera trends toward via the shutter ceiling, not enforced limits. Your chosen preset is remembered between sessions."
        },
        {
          "id": "18",
          "question": "How does the Digiscoping preset work?",
          "answer": "Digiscoping (holding or clamping the phone to a spotting scope's eyepiece) is the one AR camera preset that turns autofocus off — it locks the phone's lens at infinity so the scope's own focus knob is the only focus control. Phone autofocus otherwise hunts against the scope's narrow field of view. It also caps shutter speed to help with the shake that high magnification amplifies. Select it from the camera preset menu in the AR controls."
        },
        {
          "id": "19",
          "question": "The AR camera saw a bird but the confidence was too low — can I still keep and identify it?",
          "answer": "Yes, in tap-to-detect or manual capture mode. A shot that falls below the confidence threshold goes to a “Needs ID” strip instead of being discarded. Tap the thumbnail to choose from the model's other top guesses, search the full species list, or discard it. There's also an “Add Species Manually” button that takes a photo and lets you name the bird yourself when the model can't identify it at all. Manually identified birds save to the trip log like any other AR detection. (Continuous mode still discards its own below-threshold frames so the strip doesn't fill up.)"
        },
        {
          "id": "20",
          "question": "Can I keep more than one AR photo of the same bird?",
          "answer": "Yes. AR Bird Identification keeps every capture that clears the confidence threshold — up to a dozen of the strongest per species — and saves them all to the trip log, rather than keeping only a single best frame. The Photos screen shows every photo attached to a sighting."
        },
        {
          "id": "21",
          "question": "What does “Not recently reported near you” mean on an AR detection?",
          "answer": "It means that species hasn't shown up in real eBird activity within about 50 km of your location in the last two weeks — a signal worth a second look before confirming the ID. It only appears when location is available, and it never changes the confidence score itself — it's a separate flag alongside the model's real output."
        },
        {
          "id": "22",
          "question": "Why did my AI bird identification confidence seem low or uncertain?",
          "answer": "Confidence scores reflect the model's own certainty and are affected by real-world factors like background noise, image lighting / clarity, and how distinctive the species' call or appearance is. Low confidence doesn't necessarily mean the identification is wrong — but always cross-check with a field guide, especially for rare or unusual sightings."
        },
        {
          "id": "23",
          "question": "Can I correct or dismiss an incorrect AI detection?",
          "answer": "Yes — in Sound and Photo detection, tap “Not this” on a detected species to remove it from your session results before saving. In AR, tap a detection card to remove it."
        },
        {
          "id": "24",
          "question": "What is the AI Bird ID Assistant and how do I use it?",
          "answer": "The AI Bird ID Assistant is a conversational assistant that helps answer questions about bird identification, behavior, and habitat. Open it from Identify > Ask to have natural conversations about birds — ask questions like “What does a Cardinal look like?” or “How can I tell the difference between Cooper's Hawk and Sharp-shinned Hawk?” Bird species mentioned in responses appear as clickable cards showing photos and details, with a confidence indicator on each answer."
        },
        {
          "id": "25",
          "question": "What types of questions can I ask the AI Bird ID Assistant?",
          "answer": "The assistant handles species identification (“What does a Robin look like?”), species comparisons (“What's the difference between Cooper's Hawk and Sharp-shinned Hawk?”), habitat questions (“Where do Cardinals live?”), behavioral questions (“How do woodpeckers behave?”), and general questions about bird sounds. It draws on a local database of ~1,300 North American and European species. For best results, be specific in your questions."
        },
        {
          "id": "26",
          "question": "What is the AI Bird ID Assistant's knowledge based on?",
          "answer": "The assistant draws on a local database of roughly 1,300 North American and European bird species (identification features, size, habitat, behavior, similar species) plus optional Wikipedia summaries, and can answer questions about your own trip logs (“Have I seen a Painted Bunting?”). It does not currently cross-reference real-time eBird sightings for “birds near me” style questions — for local sighting data, use the Plan tab or Species Map instead. On Apple Intelligence-capable devices its answers are more natural and tagged “Enhanced by Apple Intelligence”; otherwise it automatically uses the built-in bird database."
        }
      ]
    },
    {
      "name": "Trips, logging & learning",
      "faqs": [
        {
          "id": "27",
          "question": "How do I log birds I've seen during my trip?",
          "answer": "Open your active trip from Trip Logs, find the bird in your itinerary, and tap the checkbox next to it to mark it as seen. You can also add notes and the number of birds spotted. These sightings automatically appear in your Life List. You can also use the “Add Sighting” button in Trip Logs to log birds outside of planned trips."
        },
        {
          "id": "28",
          "question": "How do I use the Add Sighting feature?",
          "answer": "Add Sighting lets you log birds you see outside your planned trips. From Trip Logs, tap “Add Sighting”, select the birds you spotted, then tap “Select on Map” to choose the exact location — tap anywhere on the map to set coordinates and give the location a name (e.g. “Central Park Lake” or “My Backyard”). Confirm to add the sighting to your current trip, or create a new one."
        },
        {
          "id": "29",
          "question": "How do I select and name locations for my bird sightings?",
          "answer": "When adding an ad-hoc sighting, tap “Select on Map” to open the location picker, tap anywhere on the map to set coordinates, then enter a custom name for the location (like “Central Park Lake” or “My Backyard”). Both coordinates and a name are required to save the sighting."
        },
        {
          "id": "30",
          "question": "What does “Start route from current location” do?",
          "answer": "This option changes how your trip route is planned. Normally trips are optimized starting from your custom search location; enabling this option instead creates a route starting from wherever you currently are, useful when you're searching a specific area but starting your trip from somewhere else. It only appears when your current and search locations differ."
        },
        {
          "id": "31",
          "question": "How do I view my birding locations on the Trip Map?",
          "answer": "On the Log tab, choose Trip Map from the title menu and load the map to see all your logged birding locations as markers, with the number of birds logged shown per marker. Tap any trip in the list below the map to highlight just that trip's locations and zoom to its area."
        },
        {
          "id": "32",
          "question": "What is the Life List screen?",
          "answer": "The Life List shows every bird species you've marked as “seen” across all your trips — your personal birding record. Each entry shows a thumbnail image; tap it to open the bird card, or tap the bird's name to see every location and date you've spotted that species, with a link back to the original trip log."
        },
        {
          "id": "33",
          "question": "How do I search my trip logs?",
          "answer": "Trip Logs has a search bar at the top — type a trip name, a location, or a species you saw, and the list filters live. It searches trip names, notes, start / end locations, individual stop names, and every logged species across all your trips."
        },
        {
          "id": "34",
          "question": "I logged the same outing twice — can I combine them?",
          "answer": "Yes. Go to Settings > Advanced > Find & Combine Similar Trips. It automatically groups trips that share a date and at least one matching location, so you can review likely duplicates (e.g. one logged manually and one imported from eBird) and merge them. Combining keeps every sighting and photo from each selected trip rather than picking one copy and discarding the rest — the surviving trip ends up with everything. This is different from “Remove Duplicate Trips” nearby, which only catches exact name+date matches and deletes the losing copies outright."
        },
        {
          "id": "35",
          "question": "What is the State Goals feature?",
          "answer": "State Goals tracks your progress toward seeing every official state bird from the eBird taxonomy. Set your home state in Settings, then on the Log tab choose State Birds from the title menu to see which you've spotted (checkmarked) and which remain, along with your overall completion percentage."
        },
        {
          "id": "36",
          "question": "How are sound-identified birds added to my trip logs and life list?",
          "answer": "Birds identified through sound detection are automatically added to a session trip log with the detection method, confidence score, and timestamp. When your session ends, you can merge these into an existing trip or keep them as their own trip. All sound-identified birds appear in your Life List and Big Month tracking like any other sighting."
        },
        {
          "id": "37",
          "question": "How does AI detection integrate with my existing trip plans?",
          "answer": "When you finish a Sound, Photo, or AR session and have other active trips, the app offers to merge your detections into one of them via a trip picker, or keep the session as its own separate trip. Nothing in your existing planned locations is removed or overwritten."
        },
        {
          "id": "38",
          "question": "What is the Trip Trail and how do I turn it on?",
          "answer": "The Trip Trail is the GPS path you actually walk during a trip. It records automatically when you tap “Start Trip” on a saved trip and stops when you tap “Finish Trip”. View it later from the trip's detail screen via “View Trip Trail” — your path shows as a line, and any fleet nodes reporting a position during the trip show as pins. It's per-trip, unlike Log > Trip Map, which plots logged locations across all trips."
        },
        {
          "id": "39",
          "question": "How do I use Behavior Logging to record bird behaviors?",
          "answer": "On the Log tab, tap the ••• button (top-left) and choose Behaviors, then use the Record tab. Select a species, choose from 14 behavior categories (Feeding, Nesting, Social Interaction, Territorial Display, Courtship, Foraging, Preening / Grooming, Flight Behavior, Vocalizing / Singing, Bathing, Roosting / Resting, Aggressive Behavior, Migration Movement, Other), describe what you observed, and record details like duration (using the built-in timer), number of birds, location, and weather. Behavior logs are independent of trips and automatically count toward monthly challenges. Review saved entries on that screen's History tab."
        },
        {
          "id": "40",
          "question": "How do I use Migration Tracking to record bird movements?",
          "answer": "On the Log tab, tap the ••• button (top-left) and choose Migration, then use the Record tab. Select a species, record its migration status (Actively Migrating, Staging / Resting, Arriving, Departing, Overwintering, At Breeding Grounds, or Vagrant / Off-course), plus flock size, direction, altitude, and time of day. The app automatically detects the current season for context. Migration logs are independent of trips and count toward monthly challenges. Review saved entries on that screen's History tab."
        },
        {
          "id": "41",
          "question": "How do I access and manage my Behavior and Migration logs?",
          "answer": "On the Log tab, tap the ••• button (top-left) and choose Behaviors or Migration — these are separate from your regular trip logs. Each screen's History tab lists your recorded observations with species, details, timestamps, and location names; swipe a row to delete it."
        },
        {
          "id": "42",
          "question": "How do I log behavior and migration observations quickly?",
          "answer": "Use the Behaviors and Migration screens on the Log tab (the ••• button, each with a Record and a History tab) for detailed, structured observations — these are the primary way to record behavior / migration data and are what count toward the related monthly challenges."
        },
        {
          "id": "43",
          "question": "What's the difference between trip-based observations and standalone behavior / migration logs?",
          "answer": "Trip-based observations (Trip Logs, Life List, State Birds, Big Month) are your general birding activity — species you've spotted during outings, contributing to your Life List and shareable exports. Standalone Behaviors and Migration logs are focused research observations recorded independently of trips, contributing specifically to monthly research-style challenges. Use trip logging for regular birding; use the standalone logs when documenting detailed behavior or migration patterns."
        },
        {
          "id": "44",
          "question": "How do I create and manage birding story journals?",
          "answer": "“Tell Your Story” (the ••• button on the Log tab) lets you create journals combining trip data, photos, and personal narrative. Set a date range to pull in trips, behavior logs, and migration logs from that period, write your narrative, and the app generates species and behavior summaries automatically. Export your story as text, or share a simplified version through the standard share sheet. To make changes later, open the story and tap Edit — you can update the title, narrative, date range, selected trips / logs, and photos at any time."
        },
        {
          "id": "45",
          "question": "How do Bird Challenges work?",
          "answer": "Bird Challenges are gamified activities encouraging real-world birding. Daily challenges reset each day, weekly challenges reset Mondays, and monthly challenges reset on the 1st. Access them from Learn > Bird Challenges. Progress tracks automatically as you use the app's other features — no manual entry needed."
        },
        {
          "id": "46",
          "question": "How does automatic challenge progress tracking work?",
          "answer": "The app tracks challenge progress automatically as you use it normally. Marking birds “seen” in trip logs counts toward identification and species-diversity challenges. AI sound / photo / AR detections count toward their respective challenges. Behavior and migration logs count toward monthly research challenges. Habitat type is automatically determined from location names and species data for habitat-exploration challenges. You don't need to do anything extra — just go birding and log your sightings as usual."
        },
        {
          "id": "47",
          "question": "What types of challenges are available and how do I complete them?",
          "answer": "Daily challenges focus on immediate identification, sound-detection, and photo-capture goals. Weekly challenges focus on species diversity, habitat exploration, and rare-bird discovery. Monthly challenges focus on migration tracking and behavior study, using the Behaviors and Migration screens on the Log tab (each with a Record and a History tab). All progress updates automatically as you use the app's features."
        },
        {
          "id": "48",
          "question": "How do I view my completed challenges and points?",
          "answer": "Learn > Bird Challenges shows your total points and completed-vs-total count at the top, with each daily / weekly / monthly challenge listed below showing a live progress bar, points value, and completion status."
        },
        {
          "id": "49",
          "question": "How does habitat detection work for the Habitat Explorer challenge?",
          "answer": "When you log a bird with a location, the app automatically classifies the habitat type (woodland, water, or urban) using the species' known habitat data and the location name, without any manual input needed."
        },
        {
          "id": "50",
          "question": "How does the interactive quiz system work in Learn About Birds?",
          "answer": "After marking all 5 birds in a set as learned, you take a 10-question multiple-choice quiz: photo-ID questions (\"which bird is shown?\"), field-mark questions (\"which bird has these marks?\"), plus key-feature and habitat questions. Wrong answers are drawn from each species' listed confusion species where possible. Score at least 80% to pass. The results screen lists which birds you missed and offers to re-quiz just those; missed birds also drop back for a quicker repeat, while learned birds return later on a spaced-review schedule."
        },
        {
          "id": "51",
          "question": "What is location-based learning and how does it adapt to my area?",
          "answer": "Learn About Birds fetches real eBird observations from your current (or custom) location and selects 5 birds at a time from species actually found in your area, so you're studying birds you're likely to actually encounter. Changing your location updates the content."
        },
        {
          "id": "52",
          "question": "How do I track my learning progress?",
          "answer": "The Learn tab's progress card shows birds mastered (moved into spaced review), species on your Life List, and your best day-streak. Your badge (New Birder → Birding Expert) is based on all of those plus challenges and activities completed — not just replayed points. A day counts toward your streak whenever you open the Learn tab or finish an activity."
        },
        {
          "id": "53",
          "question": "Can I mark birds as learned directly from the bird cards?",
          "answer": "Yes — each bird's detail view in Learn About Birds has a “Mark as Learned” button, plus “Open full species card” and “Ask the assistant about this bird”."
        },
        {
          "id": "54",
          "question": "How do I use Observe Mode and its challenge system?",
          "answer": "Observe Mode (Learn > Practice Observing) is a guided listen → observe → describe → compare exercise. You must complete two full rounds (listen for a bird, then describe what you see) in a session to finish the activity — this reinforces consistent identification skills rather than a single lucky guess."
        },
        {
          "id": "55",
          "question": "How does the Learn tab help me become a better birder?",
          "answer": "Four activities build different skills — Learn About Birds (recognition, with spaced review), Practice Observing (linking a sound to a bird in the field), Plan Your Trips (the guided trip walkthrough), and Bird Challenges. A Practice & Ask row then drops you straight into the assistant or Sound / Photo / AR identification. Your badge and daily streak reflect real progress: birds mastered, species seen, challenges and activities done."
        },
        {
          "id": "56",
          "question": "How do I use hotspot notes to enhance my birding locations?",
          "answer": "While browsing hotspots, you can add a personal note about a location — access points, best viewing spots, seasonal patterns, or other observations. Notes are saved locally and persist across sessions."
        }
      ]
    },
    {
      "name": "Data, photos & backup",
      "faqs": [
        {
          "id": "57",
          "question": "How can I export or share my birding trips?",
          "answer": "Open a trip in Trip Logs and use the share action to export it as a JSON file (importable by other app users), a plain-text summary shareable via email / messaging / any app that accepts the iOS share sheet, or Add to Calendar to create one all-day event per trip day. PDF export is not currently available."
        },
        {
          "id": "58",
          "question": "How do I export my trips to share with friends?",
          "answer": "Open a saved trip in Trip Logs and use the share action to export it as a JSON file or plain-text summary, then share it via email, messaging apps, or any other sharing method. Recipients can import your JSON export using the Import Trip feature."
        },
        {
          "id": "59",
          "question": "How do I import a trip from a file?",
          "answer": "From Trip Logs, tap the import button and select a trip file (.json format) from your device. Any photos included in the file are automatically saved and linked to their corresponding bird sightings, along with all metadata (date, location, species)."
        },
        {
          "id": "60",
          "question": "How do photos work with trip imports and exports?",
          "answer": "The per-trip JSON export (for sharing a trip with other app users) intentionally leaves photos and personal notes / seen-status out, keeping it a clean, shareable trip plan. If you want an export that includes your photos — for backing up or moving to a new phone — use Data Backup & Migration in Settings instead, which captures everything."
        },
        {
          "id": "61",
          "question": "Can I export my life list to compare against eBird?",
          "answer": "Yes. Open Life List and tap the share icon — this exports your full life list (not just the currently-selected filter) as a CSV with common name, scientific name, first-seen date, and sighting count, one row per species. Open it alongside an eBird life list export to compare which species appear on each."
        },
        {
          "id": "62",
          "question": "Is my birding data backed up anywhere?",
          "answer": "All your trips, sightings, logs, photos, and settings are stored locally on your device — there is currently no automatic cloud sync. To back up everything or move to a new phone, use Data Backup & Migration in Settings, which exports all of it (including photos) as one file."
        },
        {
          "id": "63",
          "question": "How do I move all my data to a new phone?",
          "answer": "Go to Settings > Advanced > Data Backup & Migration and tap Export All Data — this bundles every trip, sighting, photo, behavior / migration log, story, hotspot note, challenge progress record, and setting into one file, which you can AirDrop, save to Files / iCloud Drive, or email to yourself. On your new phone, once the app is installed, use Import All Data and select that file. Note that importing replaces whatever's currently on the destination device rather than merging — export a backup of that device first if it has data you don't want to lose."
        },
        {
          "id": "64",
          "question": "How do I change the sort order on the Photos screen?",
          "answer": "On the Log tab choose Photos from the title menu, then use the up / down arrows in the toolbar. You can sort by newest first, oldest first, species A–Z, species Z–A, or by which species has the most photos. Your choice is saved between visits. The button next to it switches between grid and list layout."
        },
        {
          "id": "65",
          "question": "What are the bird thumbnail images and bird cards?",
          "answer": "Peregrine Planner shows small thumbnail images next to bird names throughout the app, sourced from iNaturalist.org (cached for offline viewing). Tap the photo to open the bird's card: a full-size image with attribution, and — for the roughly 1,200 species in the app's bundled database — size, distinguishing field marks, habitat, behavior, seasonal patterns, and similar (confusion) species, plus quick links to eBird, Wikipedia, and iNaturalist. A few very recently renamed or split species, and any bird not yet in the database, show the photo and links only."
        },
        {
          "id": "66",
          "question": "Why don't some birds show thumbnail images, and what are placeholder bubbles?",
          "answer": "Not all bird species have photos available in the iNaturalist database, which is the source for bird thumbnails. When no image is available, you'll see a placeholder bubble with the first letter of the bird's name — tapping it still opens the bird card with whatever identification information is available. Coverage improves over time as more photographers contribute to iNaturalist."
        },
        {
          "id": "67",
          "question": "How do I access detailed bird information cards?",
          "answer": "Tap the bird's thumbnail photo (or letter placeholder) wherever one appears — the Plan list, trip logs, Life List, Big Month, State Birds, the Hotspot Browser, and the Learn tab. Tapping just the photo opens the card; tapping elsewhere on the row still does the row's normal action (selecting the bird, opening its sighting history, and so on). The card shows the species' size, field marks, habitat, behavior, seasonal patterns, and similar species from the bundled database, along with eBird / Wikipedia / iNaturalist links."
        },
        {
          "id": "68",
          "question": "How do I manage the image cache and storage?",
          "answer": "Peregrine Planner automatically caches bird thumbnail images from iNaturalist for faster loading and offline viewing. You can disable bird image thumbnails entirely in Settings if you want to reduce data usage — when disabled, you'll see simple letter placeholders instead of photos."
        },
        {
          "id": "69",
          "question": "Where does the bird data come from?",
          "answer": "All bird observation data comes from eBird.org, one of the world's largest biodiversity citizen-science projects, managed by the Cornell Lab of Ornithology. Bird thumbnail images come from iNaturalist.org."
        },
        {
          "id": "70",
          "question": "How can I contribute my bird sightings to eBird?",
          "answer": "eBird.org is where the app's own observation data comes from, and it's easy to contribute back: log your sightings in Peregrine Planner, then visit eBird.org directly to record the same observations there using their site or app. This helps support a global citizen-science project tracking bird populations and migration."
        }
      ]
    },
    {
      "name": "Mic array & camera nodes",
      "faqs": [
        {
          "id": "71",
          "question": "What is the directional mic array accessory?",
          "answer": "It's an optional, separately-built ESP32-S3 4-microphone hardware accessory that adds direction-finding to Sound detection. Once paired, tap the location icon next to a detected species during a listening session to see an arrow pointing toward it (left / right only, relative to the accessory's own forward mark) plus a getting closer / farther / steady trend. Set it up from Settings > Mic Array; when it's enabled, Mic Array also becomes its own tab. Firmware and wiring for anyone building the hardware are in the User Guide's Directional Mic Array section."
        },
        {
          "id": "72",
          "question": "Where do I find the Mic Array in the app?",
          "answer": "When “Enable Mic Array Integration” is turned on in Settings, Mic Array is its own bottom tab, bringing the directional mic array, the fleet, and the camera nodes together. When the setting is off, that tab is hidden and none of the mic-array UI appears — so if you don't have the DIY hardware, you never see it. The enable switch itself always lives in Settings > Mic Array."
        },
        {
          "id": "73",
          "question": "Why does the mic array's direction arrow update slowly or not at all?",
          "answer": "The direction only refreshes when the app confirms a fresh detection of the specific species you're tracking, not on every sound the array hears — this keeps it from jumping around on background noise or other birds, at the cost of updating less often than raw audio would. If it's not showing anything, confirm the accessory shows “Connected” in Settings > Mic Array, and try lowering the “Direction Sensitivity” slider there, which controls how confident a reading needs to be before it's shown at all."
        },
        {
          "id": "74",
          "question": "What is Radar Mode in the directional mic array?",
          "answer": "Radar Mode shows a live bearing for up to 4 species calling at the same time, instead of tracking just one. It works by isolating each species' typical call frequency range separately, so a busy multi-bird soundscape is more likely to produce a distinct direction per species rather than one reading for whichever call happens to be loudest. Toggle it on in Sound detection once the mic array is connected — it runs alongside single-species tracking, not instead of it."
        },
        {
          "id": "75",
          "question": "What's the difference between the direction arrow, Radar Mode, and the Mic Array Map?",
          "answer": "The direction arrow tracks one species at a time and points left / right relative to the array's own forward mark. Radar Mode shows a live bearing for up to 4 species at once, each separated by call frequency, still relative to the array. The Mic Array Map is different: once two or more GPS-equipped nodes are connected, it plots each node's real map position and bearing and — when their bearings line up — an estimated map position for the sound. Reach it from the Sound detection screen."
        },
        {
          "id": "76",
          "question": "What are Learned Frequency Bands in the Mic Array settings?",
          "answer": "Directional tracking narrows in on a species' typical call frequency to isolate it from background noise, starting from a general per-species estimate. The app also keeps a running average of the real frequency range it actually measures each time you track that species, and — once “Seed Tracking from Learned Data” is turned on — uses that real history instead of the general estimate once at least 3 confirmed detections have accumulated for it. Measurement happens automatically in the background whether or not the toggle is on, and can be cleared with “Reset Learned Data” in the same settings screen."
        },
        {
          "id": "77",
          "question": "How do I choose which mic array node feeds Sound detection?",
          "answer": "When the mic array or another connected fleet node is available, a “Sound source” picker appears on the Sound detection screen. Pick the Primary array or a specific Additional Node — real-time detection, single-species direction tracking, and Radar Mode all follow whichever source you select."
        },
        {
          "id": "78",
          "question": "How do I add a second mic array or a camera node?",
          "answer": "Go to Settings > Mic Array > Additional Mic Array Nodes. Tap Add Node to enter a name, type (mic-only or camera), and network address, or tap Auto-Discover Nodes to find hardware already joined to your shared Wi-Fi — discovery also works over Bluetooth before any node is connected. The original front array stays on the main Mic Array screen; this list is only for additional units. A node whose IP address changes on your network is re-matched to its existing entry automatically."
        },
        {
          "id": "79",
          "question": "Why does a mic array node need a “heading source”?",
          "answer": "To place a node on the Mic Array Map, the app needs to know where it is and which way it's facing. Fixed Pin is the usual choice for a placed node: stand at it and tap “Set from my current location” to capture both its position and its facing from your phone's GPS and compass. It's used only while the node's own GPS has no fix — a real node fix always takes over automatically, and the pin re-syncs from that fix if the node is later moved. Phone Proxy instead borrows the phone's live GPS and compass (only right when the node is carried with you). Manual Heading Only records a mounting heading but no position, so that node won't appear on the map. Compass is reserved for future hardware. You set this per node when adding it, and for the Primary array in its own Mic Array settings screen."
        },
        {
          "id": "80",
          "question": "My camera node's GPS won't get a fix. Can I still use the Mic Array Map?",
          "answer": "Yes — set that node's Heading Source to “Fixed Pin”, stand next to the node, and tap “Set from my current location” to capture its position and facing from your phone. The node then plots on the Mic Array Map and contributes to triangulation using that pinned location, even with its own GPS dead. If the node's GPS ever does get a fix, the app switches to the real position automatically and updates the stored pin. Everything else about the node — sound detection, direction tracking, photo and video capture — works regardless of GPS."
        },
        {
          "id": "81",
          "question": "How do camera nodes capture photos, and where do they go?",
          "answer": "Open the Mic Array tab's Camera section — the field screen for the camera side of the mic-array hardware. There you can set each node (the Primary array and any declared camera node) to Auto capture (it photographs a bird itself when its own audio / motion detection fires) or Manual only; “Take Photo Now” works in either mode. Captured photos land in the Camera Node Captures inbox on that same screen, where you can Save a photo to a trip with the on-device species guess, choose “Not a Bird” to route it into a Tell Your Story journal, or Discard it."
        },
        {
          "id": "82",
          "question": "How do I record and save video from a camera node?",
          "answer": "Open the Mic Array tab's Camera section and use Start Video / Stop Recording on the node's card. Recording runs on the node itself and continues even if you leave the screen. Finished clips appear in the Camera Node Videos inbox on the same screen, where you can play a clip, share it through the iOS share sheet, or Save it into a trip as a sighting you identify yourself — no automatic species identification runs on video."
        },
        {
          "id": "83",
          "question": "What is Field Debug for?",
          "answer": "Field Debug (Mic Array Nodes > Field Debug) is a troubleshooting screen for the hardware accessories. Turn on remote logging per node to see a live tail of what each node reports, filter or search those lines, and share the full or filtered log out of the app for later analysis — useful for chasing GPS or Wi-Fi issues without tethering a node to a laptop. It also shows per-node AI classify latency once the Sound detection model has been loaded."
        }
      ]
    },
    {
      "name": "Settings & app basics",
      "faqs": [
        {
          "id": "84",
          "question": "How do I search Help & Info, and what does “Enhanced by Apple Intelligence” mean?",
          "answer": "Use the search box at the top of Help & Info to instantly find matching guide sections and FAQ answers by keyword — this always works, no AI involved. On devices with Apple Intelligence available and turned on, an “Ask a question about using this app” button also appears, opening a chat where you can ask in plain language (e.g. “how do I export my trip data?”) and get an answer grounded in this same Help & Info content. The AI Bird ID Assistant (Identify > Ask) works the same way for bird questions: when Apple Intelligence is available, its answers are tagged “Enhanced by Apple Intelligence”; otherwise it automatically falls back to the app's built-in bird database. You can turn the smart assistant off in Settings if you'd rather it always use the built-in database."
        },
        {
          "id": "85",
          "question": "What are the notification settings for?",
          "answer": "The “Bird Detection Alerts” toggle in Settings controls whether the app posts a notification when a species is detected during a Sound session, showing the species name and confidence percentage."
        },
        {
          "id": "86",
          "question": "How do I set my home state and why does it matter?",
          "answer": "Set your home state in Settings. It's used by the State Birds Goals feature to filter the official state bird checklist, and by Learn About Birds as a fallback source of local species when eBird observation data isn't available for your exact location."
        },
        {
          "id": "87",
          "question": "What is “Auto-Remove Unseen Birds”?",
          "answer": "A toggle in Settings. When on, marking a trip complete automatically removes any birds in that trip you never marked as seen, so a completed trip reflects only what you actually observed. When off, unseen birds stay in the completed trip."
        },
        {
          "id": "88",
          "question": "What does “Re-check for Previous App Data” do?",
          "answer": "It's in Settings > Advanced, and only appears if data from an earlier version of the app is detected on the device. Tapping it re-offers the one-time import prompt for that older data; force-quit and reopen the app to see the prompt again."
        },
        {
          "id": "89",
          "question": "How do I report a bug or suggest a feature?",
          "answer": "Open Help & Info from the gear button at the top-right of any tab and choose Contact Support. Fill out the form and it opens your email app with a message to peregrineplanner@gmail.com ready to send. The same form on the support website works the same way."
        },
        {
          "id": "90",
          "question": "How can I support the app?",
          "answer": "The app includes an optional tip jar where you can support ongoing development. Access it from Settings under “Support the App”."
        }
      ]
    }
  ]
};
